package Gui;

import data.Contract;
import data.ContractList;
import data.Request;
import data.RequestList;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.RowSorter;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

public class PnApprovedStaff extends javax.swing.JPanel {

    Connection cn;
    ResultSet rs;
    JPanel PnShow;

    public PnApprovedStaff() {
        initComponents();
        initModel();
        initData();

    }

    public PnApprovedStaff(JPanel PnShow) {
        this.PnShow = PnShow;
        initComponents();
        initModel();
        initData();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grcheck = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txtAccNo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFrom = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTo = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        ckAll = new javax.swing.JCheckBox();
        ckPending = new javax.swing.JCheckBox();
        ckDecline = new javax.swing.JCheckBox();
        ckApproved = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbContract = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 255), new java.awt.Color(153, 153, 255)));
        setPreferredSize(new java.awt.Dimension(800, 400));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SEARCH", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 18), new java.awt.Color(0, 0, 255))); // NOI18N

        txtAccNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAccNoKeyReleased(evt);
            }
        });

        jLabel2.setText("Indentifycard");

        jLabel4.setText("From");

        jLabel5.setText("To");

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        grcheck.add(ckAll);
        ckAll.setText("All");
        ckAll.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ckAllStateChanged(evt);
            }
        });
        ckAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckAllActionPerformed(evt);
            }
        });

        grcheck.add(ckPending);
        ckPending.setText("Pending");
        ckPending.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ckPendingStateChanged(evt);
            }
        });

        grcheck.add(ckDecline);
        ckDecline.setText("Decline");
        ckDecline.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ckDeclineStateChanged(evt);
            }
        });

        grcheck.add(ckApproved);
        ckApproved.setText("Approved");
        ckApproved.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ckApprovedStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(txtFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(txtTo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jButton1)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckApproved)
                    .addComponent(ckAll))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckPending)
                    .addComponent(ckDecline))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton1)
                    .addComponent(txtTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ckAll)
                            .addComponent(ckPending))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ckDecline)
                            .addComponent(ckApproved))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        tbContract.setAutoCreateRowSorter(true);
        tbContract.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "R ID", "Indentify Card", "Name", "Grade", "Loan Amount", "Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbContract);
        if (tbContract.getColumnModel().getColumnCount() > 0) {
            tbContract.getColumnModel().getColumn(0).setMinWidth(60);
            tbContract.getColumnModel().getColumn(0).setPreferredWidth(60);
            tbContract.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.PAGE_START);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        check();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ckAllStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ckAllStateChanged
        check();

        // TODO add your handling code here:
    }//GEN-LAST:event_ckAllStateChanged

    private void ckAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckAllActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckAllActionPerformed

    private void ckPendingStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ckPendingStateChanged
        check();
        // TODO add your handling code here:
    }//GEN-LAST:event_ckPendingStateChanged

    private void ckDeclineStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ckDeclineStateChanged
        check();
        // TODO add your handling code here:
    }//GEN-LAST:event_ckDeclineStateChanged

    private void ckApprovedStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ckApprovedStateChanged
        check();
        // TODO add your handling code here:
    }//GEN-LAST:event_ckApprovedStateChanged

    private void txtAccNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAccNoKeyReleased
        check();
// TODO add your handling code here:

    }//GEN-LAST:event_txtAccNoKeyReleased
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ckAll;
    private javax.swing.JCheckBox ckApproved;
    private javax.swing.JCheckBox ckDecline;
    private javax.swing.JCheckBox ckPending;
    private javax.swing.ButtonGroup grcheck;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbContract;
    private javax.swing.JTextField txtAccNo;
    private com.toedter.calendar.JDateChooser txtFrom;
    private com.toedter.calendar.JDateChooser txtTo;
    // End of variables declaration//GEN-END:variables
    DefaultTableModel model;
    TableRowSorter<DefaultTableModel> sorter;

    public void initModel() {
        model = (DefaultTableModel) tbContract.getModel();
        sorter = (TableRowSorter<DefaultTableModel>) tbContract.getRowSorter();
        tbContract.addMouseListener(
                new MouseAdapter() {
                    public void mouseClicked(MouseEvent e) {
                        if (e.getClickCount() == 2) {
                            JTable target = (JTable) e.getSource();
                            int row = target.getSelectedRow();
                            int column = target.getSelectedColumn();
                            int rqID = Integer.parseInt(target.getValueAt(row, 0).toString());
                            RequestList rlist = new RequestList();
                            Request rq = rlist.getRequest(rqID);

                            int rperiod = rq.period;
                            Double rsalary = rq.salary;
                            String rname = rq.name;
                            String ricard = rq.icard;
                            String raddress = rq.address;
                            String rorganization = rq.organization;
                            String rphone = rq.phone;
                            Date rDob = rq.Dob;
                            Double rloanAmount = rq.loanAmount;
                            Double rcollateral = rq.collateral;
                            String rloanType = rq.loanType;
                            String rgrade = rq.grade;
                            String rstatus = rq.status;
                            boolean blstatus = true;
                            if ("Decline".equals(rstatus) || "Pending".equals(rstatus)) {
                                blstatus = false;
                            } else {
                                blstatus = true;
                            }
                            String rloanStatus = rq.loanStatus;
                            Date rday = rq.day;
                            int irate = rq.irate;
                            PnShow.removeAll();
                            PnNewCustomer a = new PnNewCustomer(PnShow, ricard, rname, rDob, raddress, rphone, rorganization, rsalary, rcollateral, rloanAmount, rloanType, rperiod, rloanStatus, rgrade, irate, blstatus, rqID);
                            //PnCheckGrade a = new PnCheckGrade();

                            PnShow.add(a);
                        }
                    }
                });
    }

    public static Date dateFormat(java.util.Date d) {
        int year = d.getYear();
        int monyh = d.getMonth();
        int date = d.getDate();
        Date re = new Date(year, monyh, date);
        return re;

    }

    private void initData() {
        RequestList list = new RequestList();
        ArrayList<Request> arrCont = list.getList();
        for (Request item : arrCont) {
            Vector v = item.toVector();
            model.addRow(v);
        }
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(SwingConstants.RIGHT);
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        tbContract.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        tbContract.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        tbContract.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
        tbContract.getColumnModel().getColumn(4).setCellRenderer(rightRenderer);
        tbContract.getColumnModel().getColumn(5).setCellRenderer(centerRenderer);
        tbContract.getColumnModel().getColumn(6).setCellRenderer(centerRenderer);

        tbContract.setShowGrid(true);
        tbContract.getTableHeader().setOpaque(false);
        tbContract.getTableHeader().setBackground(Color.blue);
        tbContract.getTableHeader().setForeground(Color.blue);
    }

    private void check() {
        ArrayList al = new ArrayList();
        RowFilter pending = RowFilter.regexFilter("Pending", 6);
        RowFilter approved = RowFilter.regexFilter("Approved", 6);
        RowFilter decline = RowFilter.regexFilter("Decline", 6);
        if (ckPending.isSelected()) {
            al.add(pending);
        }
        if (ckApproved.isSelected()) {
            al.add(approved);
        }
        if (ckDecline.isSelected()) {
            al.add(decline);
        }
        if (ckAll.isSelected()) {
        }
        String accNo = txtAccNo.getText().trim();
        Calendar datefrom = txtFrom.getCalendar();
        datefrom.add(Calendar.DAY_OF_MONTH, - 1);
        java.util.Date from = datefrom.getTime();
        Calendar dateto = txtTo.getCalendar();
        dateto.add(Calendar.DAY_OF_MONTH, + 1);
        java.util.Date to = dateto.getTime();
        if (from != null && to != null) {
            if (from.after(to)) {
                JOptionPane.showMessageDialog(null, "Ngay bat dau khong duoc lon hon nay ket thuc");
                return;
            } else {
                RowFilter begin = RowFilter.dateFilter(RowFilter.ComparisonType.AFTER, from, 5);
                RowFilter end = RowFilter.dateFilter(RowFilter.ComparisonType.BEFORE, to, 5);
                
                al.add(begin);
                al.add(end);

            }
        }

        if (accNo != null) {
            RowFilter acc = RowFilter.regexFilter(accNo, 1);
            al.add(acc);

        }

        sorter.setRowFilter(RowFilter.andFilter(al));
    }
}
