/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import data.ContractList;
import data.Customer;
import data.CustomerList;
import data.Grade;
import data.GradeList;
import data.LoanTypeList;
import data.Loantype;
import java.awt.CardLayout;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author tndkh_000
 */
public class PnCheckGrade extends javax.swing.JPanel {

    /**
     * Creates new form PnCheckGrade
     */
    public PnCheckGrade() {

        initComponents();

    }
    JPanel PnShow;
    CardLayout layCard;

    PnCheckGrade(JPanel PnShow) {
        this.PnShow = PnShow;
        initComponents();
        initData();
        LoanTypeList ll = new LoanTypeList();
        int iRate = ll.getRate(cbLoanType.getSelectedItem().toString());
        txtRate.setText(Integer.toString(iRate));

    }

    PnCheckGrade(JPanel PnShow, String inden, String salary, String coll) {
        this.PnShow = PnShow;
        initComponents();
        initData();
        LoanTypeList ll = new LoanTypeList();
        int iRate = ll.getRate(cbLoanType.getSelectedItem().toString());
        txtRate.setText(Integer.toString(iRate));
        txtIndent.setText(inden);
        txtSalary.setText(salary);
        txtColla.setText(coll);

    }

    public void goPnWaiting() {

        slider1.nextSlidPanel(PnWaiting);
        slider1.refresh();
    }

    public void goPnResault() {

        slider1.nextSlidPanel(PnResautl);
        slider1.refresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        PnCheck = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        txtColla = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        txtRate = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        btnCheck = new javax.swing.JButton();
        cbPeriod = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        txtLoanStatus = new javax.swing.JTextField();
        txtSalary = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIndent = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbLoanType = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        PnSliding = new javax.swing.JPanel();
        slider1 = new data.Slider();
        PnWaiting = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PnResautl = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btncheckpm = new javax.swing.JButton();
        txtMaxPeriod = new javax.swing.JTextField();
        btnAgree = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtGradeRs = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtMinPeriod = new javax.swing.JTextField();
        txtmaxLoan = new javax.swing.JTextField();

        jLabel10.setText("jLabel10");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gold_bars fix.jpg"))); // NOI18N

        setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 255), new java.awt.Color(153, 153, 255)));
        setPreferredSize(new java.awt.Dimension(1100, 400));
        setLayout(new java.awt.BorderLayout());

        PnCheck.setBackground(new java.awt.Color(204, 255, 204));
        PnCheck.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PnCheck.setPreferredSize(new java.awt.Dimension(550, 400));
        PnCheck.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CHECK GRADE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Agency FB", 1, 18), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel19.setText("Interes Rate : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 64, 0, 0);
        jPanel1.add(jLabel19, gridBagConstraints);

        txtColla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCollaKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 204;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 27, 0, 0);
        jPanel1.add(txtColla, gridBagConstraints);

        jLabel3.setText("%");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 4, 0, 0);
        jPanel1.add(jLabel3, gridBagConstraints);

        txtRate.setBackground(new java.awt.Color(204, 255, 204));
        txtRate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRate.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtRate.setDisabledTextColor(new java.awt.Color(0, 0, 204));
        txtRate.setDoubleBuffered(true);
        txtRate.setDragEnabled(true);
        txtRate.setEnabled(false);
        txtRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRateActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 27, 0, 0);
        jPanel1.add(txtRate, gridBagConstraints);

        jLabel16.setText("Loan Type:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 81, 0, 0);
        jPanel1.add(jLabel16, gridBagConstraints);

        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 7, 0);
        jPanel1.add(btnReset, gridBagConstraints);

        btnCheck.setText("CHECK");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 5, 7, 0);
        jPanel1.add(btnCheck, gridBagConstraints);

        cbPeriod.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "6", "9", "12", "18", "24", "36", "48", "60", "72", "84", "96", " " }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 173;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 27, 0, 0);
        jPanel1.add(cbPeriod, gridBagConstraints);

        jLabel7.setText("Collateral :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 83, 0, 0);
        jPanel1.add(jLabel7, gridBagConstraints);

        txtLoanStatus.setEnabled(false);
        txtLoanStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoanStatusActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 204;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 27, 0, 0);
        jPanel1.add(txtLoanStatus, gridBagConstraints);

        txtSalary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSalaryKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 204;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 27, 0, 0);
        jPanel1.add(txtSalary, gridBagConstraints);

        jLabel18.setText("Indentify Card :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(62, 58, 0, 0);
        jPanel1.add(jLabel18, gridBagConstraints);

        jLabel5.setText("Gross Salary:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 71, 0, 0);
        jPanel1.add(jLabel5, gridBagConstraints);

        txtIndent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIndentActionPerformed(evt);
            }
        });
        txtIndent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIndentKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 204;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(59, 27, 0, 0);
        jPanel1.add(txtIndent, gridBagConstraints);

        jLabel6.setText("Period :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 98, 0, 0);
        jPanel1.add(jLabel6, gridBagConstraints);

        cbLoanType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLoanTypeActionPerformed(evt);
            }
        });
        cbLoanType.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbLoanTypeFocusGained(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 182;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 27, 0, 0);
        jPanel1.add(cbLoanType, gridBagConstraints);

        jLabel17.setText("Loan Status :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 71, 0, 0);
        jPanel1.add(jLabel17, gridBagConstraints);

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("(*)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(62, 4, 0, 0);
        jPanel1.add(jLabel4, gridBagConstraints);

        jLabel21.setForeground(new java.awt.Color(255, 0, 0));
        jLabel21.setText("(*)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 8, 0, 6);
        jPanel1.add(jLabel21, gridBagConstraints);

        jLabel22.setForeground(new java.awt.Color(255, 0, 0));
        jLabel22.setText("(*)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 4, 0, 0);
        jPanel1.add(jLabel22, gridBagConstraints);

        PnCheck.add(jPanel1, new java.awt.GridBagConstraints());

        add(PnCheck, java.awt.BorderLayout.CENTER);

        PnSliding.setMaximumSize(new java.awt.Dimension(550, 400));
        PnSliding.setMinimumSize(new java.awt.Dimension(550, 410));
        PnSliding.setPreferredSize(new java.awt.Dimension(550, 400));
        PnSliding.setLayout(new java.awt.BorderLayout());

        slider1.setBorder(null);
        slider1.setMaximumSize(new java.awt.Dimension(550, 400));
        slider1.setPreferredSize(new java.awt.Dimension(550, 400));
        slider1.setLayout(new java.awt.CardLayout());

        PnWaiting.setMaximumSize(new java.awt.Dimension(550, 400));
        PnWaiting.setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gold_bars fix.jpg"))); // NOI18N
        PnWaiting.add(jLabel1, java.awt.BorderLayout.CENTER);

        slider1.add(PnWaiting, "card1");
        PnWaiting.getAccessibleContext().setAccessibleName("");

        PnResautl.setBackground(new java.awt.Color(204, 255, 204));
        PnResautl.setCursor(new java.awt.Cursor(java.awt.Cursor.E_RESIZE_CURSOR));
        PnResautl.setEnabled(false);
        PnResautl.setMaximumSize(new java.awt.Dimension(550, 400));
        PnResautl.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESULT", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Agency FB", 1, 18), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel11.setText("Max Loan :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 35;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 55, 0, 0);
        jPanel2.add(jLabel11, gridBagConstraints);

        jLabel12.setText("Min Period :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 32;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 55, 0, 0);
        jPanel2.add(jLabel12, gridBagConstraints);

        btncheckpm.setText("CHECK PLAN PAYMENT");
        btncheckpm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncheckpmActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 33, 48, 0);
        jPanel2.add(btncheckpm, gridBagConstraints);

        txtMaxPeriod.setBackground(new java.awt.Color(255, 255, 153));
        txtMaxPeriod.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtMaxPeriod.setEnabled(false);
        txtMaxPeriod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaxPeriodActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 138;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 18, 0, 0);
        jPanel2.add(txtMaxPeriod, gridBagConstraints);

        btnAgree.setText("AGREE AND CONTINUE");
        btnAgree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgreeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 31, 0, 0);
        jPanel2.add(btnAgree, gridBagConstraints);

        jButton9.setText("BACK TO CHECK GRADE");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 37, 0, 43);
        jPanel2.add(jButton9, gridBagConstraints);

        jLabel13.setText("Grade :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(52, 55, 0, 0);
        jPanel2.add(jLabel13, gridBagConstraints);

        txtGradeRs.setBackground(new java.awt.Color(255, 255, 153));
        txtGradeRs.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtGradeRs.setEnabled(false);
        txtGradeRs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGradeRsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 138;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(49, 18, 0, 0);
        jPanel2.add(txtGradeRs, gridBagConstraints);

        jLabel14.setText("Max Period :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 55, 0, 0);
        jPanel2.add(jLabel14, gridBagConstraints);

        txtMinPeriod.setBackground(new java.awt.Color(255, 255, 153));
        txtMinPeriod.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtMinPeriod.setEnabled(false);
        txtMinPeriod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMinPeriodActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 138;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 18, 0, 0);
        jPanel2.add(txtMinPeriod, gridBagConstraints);

        txtmaxLoan.setBackground(new java.awt.Color(255, 255, 153));
        txtmaxLoan.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtmaxLoan.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 138;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 18, 0, 0);
        jPanel2.add(txtmaxLoan, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(42, 52, 42, 65);
        PnResautl.add(jPanel2, gridBagConstraints);

        slider1.add(PnResautl, "card2");
        PnResautl.getAccessibleContext().setAccessibleDescription("");

        PnSliding.add(slider1, java.awt.BorderLayout.EAST);
        slider1.getAccessibleContext().setAccessibleDescription("");

        add(PnSliding, java.awt.BorderLayout.EAST);

        getAccessibleContext().setAccessibleParent(this);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        if (txtIndent.getText().trim().length() != 9 || txtSalary.getText().trim().length() == 0 || txtColla.getText().trim().length() == 0) {
            if (txtIndent.getText().trim().length() != 9) {
                JOptionPane.showMessageDialog(null, "Indentify must have 9 numbers");
            } else if (txtSalary.getText().trim().length() == 0) {
                JOptionPane.showMessageDialog(null, "Salary cannot be blank");
            } else {
                JOptionPane.showMessageDialog(null, "Collateral cannot be blank");
            }
        } else {

            check();
            btnCheck.setEnabled(false);
            btnReset.setEnabled(false);
            goPnResault();

        }


    }//GEN-LAST:event_btnCheckActionPerformed

    private void btnAgreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgreeActionPerformed
        PnShow.removeAll();
        PnRequest a = new PnRequest(PnShow, txtIndent.getText(), Integer.parseInt(txtSalary.getText()), Double.parseDouble(txtColla.getText()), cbLoanType.getSelectedItem().toString(), Integer.parseInt(cbPeriod.getSelectedItem().toString()), txtLoanStatus.getText(), txtGradeRs.getText(), Integer.parseInt(txtRate.getText()), Double.parseDouble(txtmaxLoan.getText()), Integer.parseInt(txtMaxPeriod.getText()), Integer.parseInt(txtMinPeriod.getText()));
        PnShow.add(a);
        PnShow.validate();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgreeActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        goPnWaiting();
        btnCheck.setEnabled(true);
        btnReset.setEnabled(true);
//        PnCheckGrade a = new PnCheckGrade(PnShow,txtIndent.getText(),txtSalary.getText(),txtColla.getText());
//        PnShow.removeAll();
//        PnShow.add(a);
//        PnShow.validate();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtIndent.setText(null);
        txtLoanStatus.setText(null);
        cbLoanType.setSelectedIndex(0);
        cbPeriod.setSelectedIndex(0);
        txtSalary.setText(null);
        txtColla.setText(null);
        btnCheck.setEnabled(true);
//        goPnWaiting();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtIndentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIndentActionPerformed
        String inden = txtIndent.getText();
        Customer cuss = new Customer();
        CustomerList cusl = new CustomerList();

        cuss = cusl.getcus(inden);
        if (cuss != null) {
            int acc = cuss.acc;

            ContractList conl = new ContractList();
            double sum = 0;
            sum = conl.SumLoan(inden);
            String test = String.format("%,.0f", sum);
            if (sum != 0) {
                txtLoanStatus.setText("Đã Nợ : " + test);
            } else {
                txtLoanStatus.setText("Chua co no");
            }
        } else {
            txtLoanStatus.setText("Chua co no");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_txtIndentActionPerformed

    private void txtLoanStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoanStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoanStatusActionPerformed

    private void txtMinPeriodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinPeriodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMinPeriodActionPerformed

    private void txtMaxPeriodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaxPeriodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaxPeriodActionPerformed

    private void txtRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRateActionPerformed

    private void cbLoanTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLoanTypeActionPerformed
        LoanTypeList ll = new LoanTypeList();
        int iRate = ll.getRate(cbLoanType.getSelectedItem().toString());
        txtRate.setText(Integer.toString(iRate));

        // TODO add your handling code here:
    }//GEN-LAST:event_cbLoanTypeActionPerformed

    private void btncheckpmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncheckpmActionPerformed
        FrPlanPayment a = new FrPlanPayment(txtRate.getText(), Integer.parseInt(txtMinPeriod.getText()), Integer.parseInt(txtMaxPeriod.getText()), Double.parseDouble(txtmaxLoan.getText()));
        a.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btncheckpmActionPerformed

    private void txtSalaryKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSalaryKeyPressed
        txtSalary.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char vChar = e.getKeyChar();
                if (!(Character.isDigit(vChar)
                        || (vChar == KeyEvent.VK_BACK_SPACE)
                        || (vChar == KeyEvent.VK_DELETE))) {
                    e.consume();
                }
            }
        });        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalaryKeyPressed

    private void txtCollaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCollaKeyPressed
        txtColla.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char vChar = e.getKeyChar();
                if (!(Character.isDigit(vChar)
                        || (vChar == KeyEvent.VK_BACK_SPACE)
                        || (vChar == KeyEvent.VK_DELETE))) {
                    e.consume();
                }
            }
        });        // TODO add your handling code here:
    }//GEN-LAST:event_txtCollaKeyPressed

    private void cbLoanTypeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbLoanTypeFocusGained
        String inden = txtIndent.getText();
        Customer cuss = new Customer();
        CustomerList cusl = new CustomerList();

        cuss = cusl.getcus(inden);
        if (cuss != null) {
            int acc = cuss.acc;

            ContractList conl = new ContractList();
            double sum = 0;
            sum = conl.SumLoan(inden);
            String test = String.format("%,.0f", sum);
            if (sum != 0) {
                txtLoanStatus.setText("Đã Nợ : " + test);
            } else {
                txtLoanStatus.setText("Chua co no");
            }
        } else {
            txtLoanStatus.setText("Chua co no");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cbLoanTypeFocusGained

    private void txtIndentKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIndentKeyPressed
        txtIndent.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char vChar = e.getKeyChar();
                if (!(Character.isDigit(vChar)
                        || (vChar == KeyEvent.VK_BACK_SPACE)
                        || (vChar == KeyEvent.VK_DELETE))) {
                    e.consume();
                }
            }
        });                // TODO add your handling code here:
    }//GEN-LAST:event_txtIndentKeyPressed

    private void txtGradeRsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGradeRsActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_txtGradeRsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnCheck;
    private javax.swing.JPanel PnResautl;
    private javax.swing.JPanel PnSliding;
    private javax.swing.JPanel PnWaiting;
    private javax.swing.JButton btnAgree;
    private javax.swing.JButton btnCheck;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btncheckpm;
    private javax.swing.JComboBox cbLoanType;
    private javax.swing.JComboBox cbPeriod;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private data.Slider slider1;
    private javax.swing.JFormattedTextField txtColla;
    private javax.swing.JTextField txtGradeRs;
    private javax.swing.JTextField txtIndent;
    private javax.swing.JTextField txtLoanStatus;
    private javax.swing.JTextField txtMaxPeriod;
    private javax.swing.JTextField txtMinPeriod;
    private javax.swing.JTextField txtRate;
    private javax.swing.JFormattedTextField txtSalary;
    private javax.swing.JTextField txtmaxLoan;
    // End of variables declaration//GEN-END:variables

    private void check() {

        GradeList grl = new GradeList();
        ArrayList<Grade> gList = grl.getListAll();
        //*** Get total Past Loan 
        ContractList conl = new ContractList();
        String inden = txtIndent.getText();
        Customer cuss = new Customer();
        CustomerList cusl = new CustomerList();
        cuss = cusl.getcus(inden);
        double sum = 0;
        if (cuss != null) {

            sum = conl.SumLoan(cuss.icard);
            goPnResault();
        }
        //*** End Get total Past Loan
        Double salary = Double.parseDouble(txtSalary.getText());
        Double Colla = Double.parseDouble(txtColla.getText());

        //*** Start phan loai grade
        for (int i = 0; i < gList.size(); i++) {

            if (i == 0) {
                if (gList.get(1).salary > salary || gList.get(1).collateral > (Colla - sum)) {

                    txtGradeRs.setText(gList.get(0).gradeID);
                    txtmaxLoan.setText(Double.toString(gList.get(0).maxAmount));
                    txtMaxPeriod.setText(Integer.toString(gList.get(0).maxPeriod));
                    txtMinPeriod.setText(Integer.toString(gList.get(0).minPeriod));

                }

            } else {
                if (salary >= gList.get(i).salary && (Colla - sum) >= gList.get(i).collateral) {
                    txtGradeRs.setText(gList.get(i).gradeID);
                    txtmaxLoan.setText(Double.toString(gList.get(i).maxAmount));
                    txtMaxPeriod.setText(Integer.toString(gList.get(i).maxPeriod));
                    txtMinPeriod.setText(Integer.toString(gList.get(i).minPeriod));

                }
            }

        }
        if (txtGradeRs.getText().contains("FAIL")) {
            btnAgree.setEnabled(false);
            btncheckpm.setEnabled(false);
        }else {
            btnAgree.setEnabled(true);
            btncheckpm.setEnabled(true);
        }
    }
    DefaultComboBoxModel model;

    private void initData() {
        model = (DefaultComboBoxModel) cbLoanType.getModel();

        LoanTypeList bl = new LoanTypeList();
        for (Loantype item : bl.getList()) {
            model.addElement(item.toVector().toString().replaceAll("[\\[\\]]", ""));
        }
    }
}
