/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import data.Details;
import data.DetailsList;
import data.PlanPayment;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.RowFilter;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author tndkh_000
 */
public class PnListOfCustomer extends javax.swing.JPanel {

    /**
     * Creates new form PnListOfCustomer
     */
    public PnListOfCustomer() {
        initComponents();
        initData();

    }
    JPanel PnShow;

    PnListOfCustomer(JPanel PnShow) {
        this.PnShow = PnShow;
        initComponents();
        initData();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        grBtn = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCusList = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        rbInden = new javax.swing.JRadioButton();
        rbName = new javax.swing.JRadioButton();
        rbStatus = new javax.swing.JRadioButton();
        btnSearch = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 255), new java.awt.Color(153, 153, 255)));
        setLayout(new java.awt.BorderLayout());

        tbCusList.setAutoCreateRowSorter(true);
        tbCusList.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 255), new java.awt.Color(153, 153, 255)));
        tbCusList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Contract ID", "Full Name", "Indentify Card", "Loan Type", "I.Rate", "Loan Amount", "Remaining Amount", "Period", "Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbCusList);
        if (tbCusList.getColumnModel().getColumnCount() > 0) {
            tbCusList.getColumnModel().getColumn(0).setPreferredWidth(50);
            tbCusList.getColumnModel().getColumn(1).setPreferredWidth(200);
            tbCusList.getColumnModel().getColumn(2).setPreferredWidth(50);
            tbCusList.getColumnModel().getColumn(3).setPreferredWidth(50);
            tbCusList.getColumnModel().getColumn(4).setPreferredWidth(50);
            tbCusList.getColumnModel().getColumn(5).setPreferredWidth(100);
            tbCusList.getColumnModel().getColumn(6).setPreferredWidth(100);
            tbCusList.getColumnModel().getColumn(7).setPreferredWidth(50);
            tbCusList.getColumnModel().getColumn(8).setPreferredWidth(50);
            tbCusList.getColumnModel().getColumn(9).setPreferredWidth(50);
        }
        tbCusList.getAccessibleContext().setAccessibleDescription("");

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SEARCH", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 18), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel1.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 153;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(36, 173, 0, 0);
        jPanel1.add(txtSearch, gridBagConstraints);

        grBtn.add(rbInden);
        rbInden.setText("Identify");
        rbInden.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 18, 18, 0);
        jPanel1.add(rbInden, gridBagConstraints);

        grBtn.add(rbName);
        rbName.setText("Name");
        rbName.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 18, 18, 0);
        jPanel1.add(rbName, gridBagConstraints);

        grBtn.add(rbStatus);
        rbStatus.setText("Status");
        rbStatus.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 18, 18, 0);
        jPanel1.add(rbStatus, gridBagConstraints);

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 18, 18, 342);
        jPanel1.add(btnSearch, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        search();
// TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.ButtonGroup grBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbInden;
    private javax.swing.JRadioButton rbName;
    private javax.swing.JRadioButton rbStatus;
    private javax.swing.JTable tbCusList;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
    DefaultTableModel model;
    TableRowSorter<TableModel> sorter;

    private void initData() {
        model = (DefaultTableModel) tbCusList.getModel();
        sorter = (TableRowSorter<TableModel>) tbCusList.getRowSorter();
        model.setRowCount(0);
        DetailsList bl = new DetailsList();
        for (Details item : bl.getcuslist()) {
            model.addRow(item.toVector2());

        }
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(SwingConstants.RIGHT);
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        tbCusList.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        tbCusList.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        tbCusList.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
        tbCusList.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);
        tbCusList.getColumnModel().getColumn(5).setCellRenderer(rightRenderer);
        tbCusList.getColumnModel().getColumn(6).setCellRenderer(rightRenderer);
        tbCusList.getColumnModel().getColumn(7).setCellRenderer(centerRenderer);
        tbCusList.getColumnModel().getColumn(8).setCellRenderer(centerRenderer);
        tbCusList.getColumnModel().getColumn(9).setCellRenderer(centerRenderer);
        tbCusList.setShowGrid(true);
        tbCusList.getTableHeader().setOpaque(false);
        tbCusList.getTableHeader().setBackground(Color.blue);
        tbCusList.getTableHeader().setForeground(Color.blue);
    }

    private void search() {
        
        String srch = txtSearch.getText().trim();

        if (rbInden.isSelected()) {
            RowFilter sh = RowFilter.regexFilter("(?i)"+srch, 2);
            sorter.setRowFilter(sh);
        } else if (rbName.isSelected()) {
            RowFilter sh = RowFilter.regexFilter("(?i)"+srch, 1);
            sorter.setRowFilter(sh);
        } else if (rbStatus.isSelected()) {
            RowFilter sh = RowFilter.regexFilter("(?i)"+srch, 9);
            sorter.setRowFilter(sh);
        }

        
       
    }

}
