/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import data.Contract;
import data.ContractList;
import data.Customer;
import data.CustomerList;
import data.MyLib;
import data.PlanPayment;
import data.Request;
import data.RequestList;
import java.sql.Date;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author tndkh_000
 */
public class PnNewCustomer extends javax.swing.JPanel {

    /**
     * Creates new form PnNewCustomer
     */
    public PnNewCustomer() {
        initComponents();
    }
    JPanel PnShow;

//    PnNewCustomer(JPanel PnShow, String indent, String name, Date dob, String Add, String phone, String company, double salary, double colateral, double loanAmout, String loanType, int period, String loanStatus, String grade, int iRate) {
//        this.PnShow = PnShow;
//        initComponents();
//        txtAcc.setEnabled(false);
//        txtindentify.setEnabled(false);
//        txtSalary.setEnabled(false);
//        txtColl.setEnabled(false);
//        NumberFormat formatphi = new DecimalFormat("#,###");
//        txtindentify.setText(indent);
//        txtName.setText(name);
//        txtDob.setDate(dob);
//        txtAddress.setText(Add);
//        txtPhone.setText(phone);
//        txtJob.setText(company);
//        txtSalary.setText(formatphi.format(salary));
//        txtColl.setText(formatphi.format(colateral));
//        txtLoanAmount.setText(formatphi.format(loanAmout));
//        txtLoanType.setText(loanType);
//        spPeriod.setValue(period);
//        txtLoanStatus.setText(loanStatus);
//        txtGrade.setText(grade);
//        txtIntRate.setText(Integer.toString(iRate));
//        initData();
//
//    }
    PnNewCustomer(JPanel PnShow, String indent, String name, Date dob, String Add, String phone, String company, double salary, double colateral, double loanAmout, String loanType, int period, String loanStatus, String grade, int iRate, boolean add, int rqID) {
        this.PnShow = PnShow;
        initComponents();
        txtAcc.setEnabled(false);
        txtindentify.setEnabled(false);
        txtSalary.setEnabled(false);
        txtColl.setEnabled(false);
        NumberFormat formatphi = new DecimalFormat("#,###");
        txtindentify.setText(indent);
        txtName.setText(name);
        txtDob.setDate(dob);
        txtAddress.setText(Add);
        txtPhone.setText(phone);
        txtJob.setText(company);
        txtSalary.setText(formatphi.format(salary));
        txtColl.setText(formatphi.format(colateral));
        txtLoanAmount.setText(formatphi.format(loanAmout));
        txtLoanType.setText(loanType);
        spPeriod.setValue(period);
        txtLoanStatus.setText(loanStatus);
        txtGrade.setText(grade);
        txtIntRate.setText(Integer.toString(iRate));
        btnAppcept.setEnabled(add);
        txtRqID.setText(Integer.toString(rqID));
        initData();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        birthdayEvaluator1 = new com.toedter.calendar.demo.BirthdayEvaluator();
        birthdayEvaluator2 = new com.toedter.calendar.demo.BirthdayEvaluator();
        jLocaleChooserBeanInfo1 = new com.toedter.components.JLocaleChooserBeanInfo();
        txtRqID = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        txtJob = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtColl = new javax.swing.JTextField();
        txtGrade = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtAcc = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtindentify = new javax.swing.JTextField();
        txtLoanStatus = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtLoanType = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtSalary = new javax.swing.JFormattedTextField();
        txtLoanAmount = new javax.swing.JFormattedTextField();
        btnAppcept = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtDob = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        spPeriod = new javax.swing.JSpinner();
        txtPhone = new javax.swing.JFormattedTextField();
        txtIntRate = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();

        txtRqID.setText("jTextField1");

        setBackground(new java.awt.Color(204, 255, 204));
        setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 255), new java.awt.Color(153, 153, 255)));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NEW CONTRACT", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Agency FB", 1, 18), new java.awt.Color(51, 51, 255))); // NOI18N
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel9.setText("Loan Amount :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 24, 0, 0);
        jPanel1.add(jLabel9, gridBagConstraints);

        jLabel6.setText("Period :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 106, 0, 0);
        jPanel1.add(jLabel6, gridBagConstraints);

        jLabel8.setText("Phone :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 20, 0, 0);
        jPanel1.add(jLabel8, gridBagConstraints);

        jLabel10.setText("Collateral :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 91, 0, 0);
        jPanel1.add(jLabel10, gridBagConstraints);

        txtAddress.setForeground(new java.awt.Color(51, 51, 255));
        txtAddress.setDisabledTextColor(new java.awt.Color(0, 0, 255));
        txtAddress.setEnabled(false);
        txtAddress.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 360;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 16, 0, 0);
        jPanel1.add(txtAddress, gridBagConstraints);

        txtJob.setForeground(new java.awt.Color(51, 51, 255));
        txtJob.setDisabledTextColor(new java.awt.Color(0, 0, 255));
        txtJob.setEnabled(false);
        txtJob.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 360;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 16, 0, 0);
        jPanel1.add(txtJob, gridBagConstraints);

        jLabel11.setText("Interest Rate :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 31;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 18, 0, 0);
        jPanel1.add(jLabel11, gridBagConstraints);

        txtName.setForeground(new java.awt.Color(51, 51, 255));
        txtName.setDisabledTextColor(new java.awt.Color(0, 0, 255));
        txtName.setEnabled(false);
        txtName.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 360;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 16, 0, 0);
        jPanel1.add(txtName, gridBagConstraints);

        txtColl.setForeground(new java.awt.Color(51, 51, 255));
        txtColl.setDisabledTextColor(new java.awt.Color(0, 0, 255));
        txtColl.setEnabled(false);
        txtColl.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 360;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 16, 0, 0);
        jPanel1.add(txtColl, gridBagConstraints);

        txtGrade.setForeground(new java.awt.Color(51, 51, 255));
        txtGrade.setDisabledTextColor(new java.awt.Color(0, 0, 255));
        txtGrade.setEnabled(false);
        txtGrade.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 20;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 53;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 18, 0, 0);
        jPanel1.add(txtGrade, gridBagConstraints);

        jLabel16.setText("Grade : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 5, 0, 0);
        jPanel1.add(jLabel16, gridBagConstraints);

        txtAcc.setForeground(new java.awt.Color(51, 51, 255));
        txtAcc.setDisabledTextColor(new java.awt.Color(0, 0, 255));
        txtAcc.setEnabled(false);
        txtAcc.setPreferredSize(new java.awt.Dimension(50, 30));
        txtAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAccActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 20;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 275;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 18, 0, 16);
        jPanel1.add(txtAcc, gridBagConstraints);

        jLabel15.setText("Account No. :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 30, 0, 0);
        jPanel1.add(jLabel15, gridBagConstraints);

        txtindentify.setForeground(new java.awt.Color(51, 51, 255));
        txtindentify.setDisabledTextColor(new java.awt.Color(0, 0, 255));
        txtindentify.setEnabled(false);
        txtindentify.setPreferredSize(new java.awt.Dimension(50, 30));
        txtindentify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtindentifyActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 360;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 16, 0, 0);
        jPanel1.add(txtindentify, gridBagConstraints);

        txtLoanStatus.setForeground(new java.awt.Color(51, 51, 255));
        txtLoanStatus.setDisabledTextColor(new java.awt.Color(0, 0, 255));
        txtLoanStatus.setEnabled(false);
        txtLoanStatus.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 360;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 16, 0, 0);
        jPanel1.add(txtLoanStatus, gridBagConstraints);

        jLabel14.setText("Indentify Card :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 67, 0, 0);
        jPanel1.add(jLabel14, gridBagConstraints);

        txtLoanType.setForeground(new java.awt.Color(51, 51, 255));
        txtLoanType.setDisabledTextColor(new java.awt.Color(0, 0, 255));
        txtLoanType.setEnabled(false);
        txtLoanType.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 20;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 275;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 16);
        jPanel1.add(txtLoanType, gridBagConstraints);

        jLabel13.setText("Loan Status : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 69, 0, 0);
        jPanel1.add(jLabel13, gridBagConstraints);

        jLabel7.setText("Salary :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 20, 0, 0);
        jPanel1.add(jLabel7, gridBagConstraints);

        jLabel5.setText("Company :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 91, 0, 0);
        jPanel1.add(jLabel5, gridBagConstraints);

        txtSalary.setForeground(new java.awt.Color(51, 51, 255));
        txtSalary.setDisabledTextColor(new java.awt.Color(0, 0, 255));
        txtSalary.setEnabled(false);
        txtSalary.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 20;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 275;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 16);
        jPanel1.add(txtSalary, gridBagConstraints);

        txtLoanAmount.setForeground(new java.awt.Color(51, 51, 255));
        txtLoanAmount.setDisabledTextColor(new java.awt.Color(0, 0, 255));
        txtLoanAmount.setEnabled(false);
        txtLoanAmount.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 20;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 275;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 16);
        jPanel1.add(txtLoanAmount, gridBagConstraints);

        btnAppcept.setText("Appcept");
        btnAppcept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAppceptActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 142, 10, 0);
        jPanel1.add(btnAppcept, gridBagConstraints);

        jLabel2.setText("Full Name :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 91, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        txtDob.setBackground(new java.awt.Color(255, 255, 255));
        txtDob.setForeground(new java.awt.Color(0, 0, 255));
        txtDob.setEnabled(false);
        txtDob.setMinSelectableDate(new java.util.Date(-62135791127000L));
        txtDob.setMinimumSize(new java.awt.Dimension(30, 25));
        txtDob.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 20;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 254;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 18, 0, 16);
        jPanel1.add(txtDob, gridBagConstraints);

        jLabel3.setText("DoB :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 31, 0, 0);
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabel12.setText("Loan Type : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 36, 0, 0);
        jPanel1.add(jLabel12, gridBagConstraints);

        jLabel4.setText("Address :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 97, 0, 0);
        jPanel1.add(jLabel4, gridBagConstraints);

        spPeriod.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 43;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 17, 0, 0);
        jPanel1.add(spPeriod, gridBagConstraints);

        txtPhone.setForeground(new java.awt.Color(51, 51, 255));
        txtPhone.setDisabledTextColor(new java.awt.Color(0, 0, 255));
        txtPhone.setEnabled(false);
        txtPhone.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 20;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 275;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 18, 0, 16);
        jPanel1.add(txtPhone, gridBagConstraints);

        txtIntRate.setForeground(new java.awt.Color(51, 51, 255));
        txtIntRate.setDisabledTextColor(new java.awt.Color(0, 0, 255));
        txtIntRate.setEnabled(false);
        txtIntRate.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 32;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 116;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 10, 0, 16);
        jPanel1.add(txtIntRate, gridBagConstraints);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 32, 10, 0);
        jPanel1.add(btnCancel, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAppceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppceptActionPerformed
        ContractList conl = new ContractList();
        String iCard = txtindentify.getText().trim();

        //Add new Customer
        String name = txtName.getText().trim();
        String Add = txtAddress.getText().trim();
        String job = txtJob.getText().trim();
        java.util.Date utilDate = new java.util.Date();
        utilDate = txtDob.getDate();
        java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
//            Date DOB = (Date) txtDob.getDate();
//            java.sql.Date sqlDate = DOB.getTime();
        int acc = 0;
        String phone = txtPhone.getText().trim();
        int salary = Integer.parseInt(txtSalary.getText().trim().replaceAll("[\\.\\,]", ""));
        if ("NEW CUSTOMER".equals(txtAcc.getText())) {
            Customer cus = new Customer(acc, name, iCard, sqlDate, Add, job, phone, salary);
            CustomerList cl = new CustomerList();
            cl.insert(cus);
        } else {
            acc = Integer.parseInt(txtAcc.getText().trim());
            Customer cus = new Customer(acc, name, iCard, sqlDate, Add, job, phone, salary);
            CustomerList cl = new CustomerList();
            cl.update(cus);
        }
        btnAppcept.setEnabled(false);
        //end Add new customer

        //Add new Contrac
        int id = 0;
        String grade = txtGrade.getText().trim();
        Calendar d = Calendar.getInstance();
        java.util.Date date = d.getTime();
        java.sql.Date sqlDatecon = new java.sql.Date(date.getTime());
        int acccon = conl.getacc(iCard);
        Double Collateral = Double.parseDouble(txtColl.getText().trim().replaceAll("[\\.\\,]", ""));
        int Period = (int) spPeriod.getValue();
        Double loanAmout = Double.parseDouble(txtLoanAmount.getText().trim().replaceAll("[\\.\\,]", ""));
        String loanType = txtLoanType.getText().trim();
        String loanStatus = txtLoanStatus.getText().trim();

        Contract con = new Contract(id, acccon, loanType, loanAmout, Collateral, grade, Period, sqlDatecon, "Normal", loanStatus);
        int ID = conl.insert(con);
        JOptionPane.showMessageDialog(null, "Add Contract Success !");

        // End add new Contrac
        //Star add new details Contrac
        double goc = 0, goctrongky, gocconlai = 0, lai, laitrongky, tongcong;
        int ky;

        goc = Double.parseDouble(txtLoanAmount.getText().replaceAll("[\\.\\,]", ""));
        lai = Double.parseDouble(txtIntRate.getText());
        ky = Integer.parseInt(spPeriod.getValue().toString());
        goctrongky = goc / ky;
        gocconlai = goc - gocconlai;
        laitrongky = gocconlai * (lai / 100) / 12;
        tongcong = goctrongky + laitrongky;
        Calendar ngaytbatdau = Calendar.getInstance();
        java.util.Date ngaybatdauulti = ngaytbatdau.getTime();
        java.sql.Date ngaybatdausql = new java.sql.Date(ngaybatdauulti.getTime());
        Calendar ngaythanhtoan = Calendar.getInstance();
        ngaythanhtoan.add(Calendar.MONTH, 1);
        java.util.Date ngaythanhtoanulti = ngaythanhtoan.getTime();
        java.sql.Date ngaythanhtoansql = new java.sql.Date(ngaythanhtoanulti.getTime());
        PlanPayment a = new PlanPayment(ID, 1, goctrongky, gocconlai, laitrongky, tongcong, ngaybatdausql, ngaythanhtoansql, "Not Yet", iCard, 0, null);
        ArrayList<PlanPayment> detail = new ArrayList<>();
        detail.add(a);

        for (int i = 1; i < ky; i++) {
            gocconlai = gocconlai - goctrongky;
            laitrongky = gocconlai * (lai / 100) / 12;
            tongcong = goctrongky + laitrongky;
            ngaythanhtoan = Calendar.getInstance();
            ngaythanhtoan.add(Calendar.MONTH, i + 1);
            ngaythanhtoanulti = ngaythanhtoan.getTime();
            ngaythanhtoansql = new java.sql.Date(ngaythanhtoanulti.getTime());
            PlanPayment b = new PlanPayment(ID, i + 1, goctrongky, gocconlai, laitrongky, tongcong, ngaybatdausql, ngaythanhtoansql, "Not Yet", iCard, 0, null);
            detail.add(b);
        }
        for (PlanPayment planPayment : detail) {
            planPayment.addlisttiDatabase(planPayment);
        }

        RequestList list = new RequestList();
        list.delete(Integer.parseInt(txtRqID.getText()));
        HashMap map = new HashMap();
        map.put("conID_para", ID);
        map.put("name_para", name);
        map.put("dob_para", utilDate.toString());
        map.put("phone_para", phone);
        map.put("grade_para", grade);
        map.put("loantype_para", loanType);
        map.put("salary_para", salary);
        map.put("inden_para", txtindentify.getText());
        map.put("add_para", Add);
        map.put("organ_para", job);
        map.put("amount_para", loanAmout);
        map.put("coll_para", Collateral);
        map.put("rate_para", txtIntRate.getText());
        map.put("accNo_para", conl.getacc(txtindentify.getText()));
        String url = "report/RpContract.jrxml";
        try {
            JasperReport jas_report = JasperCompileManager.compileReport(url);
            JasperPrint jas_print = JasperFillManager.fillReport(jas_report, map, MyLib.getCon());
            JasperViewer.viewReport(jas_print, false);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, "File not found");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAppceptActionPerformed

    private void txtAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccActionPerformed

    private void txtindentifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtindentifyActionPerformed
        ContractList conl = new ContractList();
        String iCard = txtindentify.getText().trim();
        if (conl.getacc(iCard) == 0) {
            txtAcc.setText("NEW CUSTOMER");

        } else {
            Customer cus = new Customer();
            CustomerList cl = new CustomerList();
            cus = cl.getcus(iCard);
            txtAcc.setText(Integer.toString(cus.acc));

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_txtindentifyActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        PnShow.removeAll();
        PnApprovedStaff a = new PnApprovedStaff(PnShow);
        PnShow.add(a);
        PnShow.validate();

// TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.demo.BirthdayEvaluator birthdayEvaluator1;
    private com.toedter.calendar.demo.BirthdayEvaluator birthdayEvaluator2;
    private javax.swing.JButton btnAppcept;
    private javax.swing.JButton btnCancel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.toedter.components.JLocaleChooserBeanInfo jLocaleChooserBeanInfo1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner spPeriod;
    private javax.swing.JTextField txtAcc;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtColl;
    private com.toedter.calendar.JDateChooser txtDob;
    private javax.swing.JTextField txtGrade;
    private javax.swing.JTextField txtIntRate;
    private javax.swing.JTextField txtJob;
    private javax.swing.JFormattedTextField txtLoanAmount;
    private javax.swing.JTextField txtLoanStatus;
    private javax.swing.JTextField txtLoanType;
    private javax.swing.JTextField txtName;
    private javax.swing.JFormattedTextField txtPhone;
    private javax.swing.JTextField txtRqID;
    private javax.swing.JFormattedTextField txtSalary;
    private javax.swing.JTextField txtindentify;
    // End of variables declaration//GEN-END:variables

    private void initData() {
        ContractList conl = new ContractList();
        String iCard = txtindentify.getText().trim();
        if (conl.getacc(iCard) == 0) {
            txtAcc.setText("NEW CUSTOMER");

        } else {
            Customer cus = new Customer();
            CustomerList cl = new CustomerList();
            cus = cl.getcus(iCard);
            txtAcc.setText(Integer.toString(cus.acc));

        }
    }
}
