/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import data.Contract;
import data.ContractList;
import data.Grade;
import data.GradeList;
import data.MyLib;
import java.awt.Panel;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Date;
import java.text.DateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Mihawk
 */
public class pnOverduePayment extends javax.swing.JPanel {

    JPanel PnShow;
    public int contractID, row;

    public pnOverduePayment() {
        initComponents();
        initData();
    }

    public pnOverduePayment(JPanel pnShow) {
        this.PnShow = pnShow;
        initComponents();
        initData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbContract = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        tbContract.setAutoCreateRowSorter(true);
        tbContract.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Contract ID", "Account No", "Payment Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbContract.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbContractMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbContract);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void tbContractMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbContractMouseClicked
      
    }//GEN-LAST:event_tbContractMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
                
                String url= "report/RpOverdue.jrxml";
                JasperReport jas_report = JasperCompileManager.compileReport(url);
                JasperPrint Jast_print = JasperFillManager.fillReport(jas_report,  null, MyLib.getCon());
                JasperViewer.viewReport(Jast_print, false);
            } catch (Exception e) {
                e.printStackTrace();
            }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbContract;
    // End of variables declaration//GEN-END:variables
    DefaultTableModel model;

    private void initData() {
        model = (DefaultTableModel) tbContract.getModel();
        ContractList list = new ContractList();
        ArrayList<Contract> cList = list.getList();
        for (Contract item : cList) {
            if (item.status.equalsIgnoreCase("Overdue")) {
                model.addRow(item.toVectorOver());
            }
        }
        tbContract.addMouseListener(
                new MouseAdapter() {
                    public void mouseClicked(MouseEvent e) {
                        if (e.getClickCount() == 2) {
                            JTable target = (JTable) e.getSource();
                            int row = target.getSelectedRow();
                            contractID = Integer.parseInt(tbContract.getValueAt(row, 0).toString());
                            PnTracking detail = new PnTracking(contractID);
                            JOptionPane.showMessageDialog(null, detail, "Details", JOptionPane.PLAIN_MESSAGE, null);
                            //JOptionPane.showMessageDialog(null, detail,JOptionPane.PLAIN_MESSAGE);
//                            int i = JOptionPane.showConfirmDialog(null, detail, "Details", 0, JOptionPane.PLAIN_MESSAGE);
//                            java.util.Date now = new java.util.Date();
//                            if (i == 0) {
//                                model.setValueAt(DateFormat.getInstance().format(now), row, 3);
//                            }

                            //PnCheckGrade a = new PnCheckGrade();
                        }
                    }

                });
    }
}
