/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import data.ContractList;
import data.Customer;
import data.CustomerList;
import data.Details;
import data.DetailsList;
import data.Fine;
import data.FineList;
import data.MyLib;
import data.PlanPayment;
import java.awt.Color;
//import java.sql.Date;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author tndkh_000
 */
public class PnPayment extends javax.swing.JPanel {

    /**
     * Creates new form PnPayment
     */
    public PnPayment() {
        initComponents();
        initModel();

    }
    JPanel PnShow;
    ArrayList<Fine> fList;

    public PnPayment(JPanel PnShow) {
        this.PnShow = PnShow;
        initComponents();
        initModel();
    }
    DefaultTableModel model;
    TableRowSorter<TableModel> sorter;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtinden = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbContract = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDOB = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        txtCompany = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtAdd = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDetail = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        btnPayment = new javax.swing.JButton();
        txtPeriod = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtFine = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtLoan = new javax.swing.JTextField();
        txtRemain = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 255), new java.awt.Color(153, 153, 255)));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INPUT", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 18), new java.awt.Color(51, 51, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Indentify No :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        txtinden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtindenActionPerformed(evt);
            }
        });
        jPanel1.add(txtinden, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 116, -1));

        jLabel2.setText("Contract No :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        cbContract.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Chọn HĐ" }));
        cbContract.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbContractFocusGained(evt);
            }
        });
        cbContract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbContractActionPerformed(evt);
            }
        });
        jPanel1.add(cbContract, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 116, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CUSTOMER DETAIL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 18), new java.awt.Color(0, 51, 255))); // NOI18N

        jLabel3.setText("Name :");

        jLabel4.setText("Address :");

        txtName.setEditable(false);

        txtPhone.setEditable(false);
        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });

        jLabel5.setText("Day of Birth :");

        txtDOB.setEnabled(false);
        txtDOB.setMaxSelectableDate(new java.util.Date(253370743292000L));
        txtDOB.setMaximumSize(new java.awt.Dimension(91, 20));

        jLabel6.setText("Company :");

        txtCompany.setEditable(false);

        jLabel7.setText("Phone :");

        txtAdd.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAdd)
                            .addComponent(txtName))
                        .addGap(73, 73, 73)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDOB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtAdd, txtCompany, txtName});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5)
                    .addComponent(txtDOB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(txtAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(txtCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtAdd, txtCompany, txtName, txtPhone});

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(452, 100));

        tbDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Period", "Principal/P", "Interes/P", "Fine", "Amount", "Remain", "Payment Due", "Status", "Payment Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbDetail);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PAYMENT", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 18), new java.awt.Color(0, 51, 255))); // NOI18N

        jLabel12.setText("Period :");

        jLabel13.setText("Amount :");

        txtAmount.setEditable(false);

        btnPayment.setText("Payment");
        btnPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentActionPerformed(evt);
            }
        });

        txtPeriod.setEditable(false);

        jLabel10.setText("Fine");

        txtFine.setEditable(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12))
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFine, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnPayment)
                .addGap(92, 92, 92))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10)
                    .addComponent(txtFine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPayment)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PAYMENT DETAIL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 18), new java.awt.Color(51, 51, 255))); // NOI18N

        jLabel9.setText("Remaining :");

        jLabel8.setText("Loan Amount :");

        txtLoan.setEditable(false);

        txtRemain.setEditable(false);
        txtRemain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRemainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLoan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRemain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtLoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtRemain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void txtRemainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRemainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRemainActionPerformed
    DefaultComboBoxModel cbmodel;
    private void txtindenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtindenActionPerformed
        String inden = txtinden.getText().trim();
        ContractList list = new ContractList();

        cbmodel = (DefaultComboBoxModel) cbContract.getModel();
        cbmodel.removeAllElements();
        if (!list.getContractID(inden).isEmpty()) {
            for (Integer a : list.getContractID(inden)) {
                cbmodel.addElement(a);
            }
            CustomerList clist = new CustomerList();
            Customer cus = clist.getcus(inden);
            txtAdd.setText(cus.address);
            txtCompany.setText(cus.organization);
            txtName.setText(cus.name);
            txtDOB.setDate(cus.Dob);
            txtPhone.setText(cus.phone);
        } else {

            txtinden.requestFocus();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_txtindenActionPerformed

    private void cbContractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbContractActionPerformed
        btnPayment.setEnabled(true);
        if (cbmodel.getSize() != 0) {
            model.setRowCount(0);
            PlanPayment bl = new PlanPayment();
            for (PlanPayment item : bl.getacc(Integer.parseInt(cbContract.getSelectedItem().toString()))) {
                model.addRow(item.toVector2());
            }
            DetailsList list = new DetailsList();
            Details newdetails = new Details();
            newdetails = list.getdetail(Integer.parseInt(cbContract.getSelectedItem().toString()));
            PlanPayment Plan = new PlanPayment();
            int Paid = Plan.getremain(Integer.parseInt(cbContract.getSelectedItem().toString()));
            double remain = newdetails.loanAmount - Paid;
            NumberFormat fomat = new DecimalFormat("#,###.##");
            txtLoan.setText(fomat.format(newdetails.loanAmount));
            txtRemain.setText(fomat.format(remain));
            for (int i = 0; i < model.getRowCount(); i++) {
                if (model.getValueAt(i, 7).toString().equalsIgnoreCase("Overdue")) {
                    txtPeriod.setText(model.getValueAt(i, 0).toString());
                    txtAmount.setText(model.getValueAt(i, 4).toString());
                    txtFine.setText(model.getValueAt(i, 3).toString());

                    break;
                } else if (!"Paid".equals(model.getValueAt(i, 7).toString())) {
                    txtPeriod.setText(model.getValueAt(i, 0).toString());
                    txtAmount.setText(model.getValueAt(i, 4).toString());
                    txtFine.setText("0");
                    break;
                } else if (i == model.getRowCount() - 1) {
                    txtPeriod.setText("All Paid");
                    txtAmount.setText("All Paid");
                    btnPayment.setEnabled(false);
                }
            }

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_cbContractActionPerformed

    private void btnPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentActionPerformed
        int reply = JOptionPane.showConfirmDialog(null, "Are u sure ?", "Payment Confirmation", 2);
        if (reply == JOptionPane.YES_OPTION) {
            DetailsList list = new DetailsList();
            java.util.Date utilDate = new java.util.Date();
            java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
            int ctID = Integer.parseInt(cbContract.getSelectedItem().toString());
            list.update(Integer.parseInt(cbContract.getSelectedItem().toString()), Integer.parseInt(txtPeriod.getText().toString()), "Paid", sqlDate);
            PlanPayment a = new PlanPayment();
            if (a.getNomarl(ctID)) {
                ContractList con = new ContractList();
                con.updateNomarl(ctID);
            }
            int period = Integer.parseInt(txtPeriod.getText()) - 1;
            
            model.setValueAt("Paid", period, 7);
            model.setValueAt(sqlDate, period, 8);
            try {
                HashMap map = new HashMap();
                map.put("month_para", txtPeriod.getText());
                map.put("name_para", txtName.getText());
                map.put("date_para", new Date());
                map.put("contractID_para", cbContract.getSelectedItem());
                map.put("total_para", txtAmount.getText());
                String url = "report/RpBill.jrxml";
                JasperReport jas_report = JasperCompileManager.compileReport(url);
                JasperPrint Jast_print = JasperFillManager.fillReport(jas_report, map, MyLib.getCon());
                JasperViewer.viewReport(Jast_print, false);
            } catch (Exception e) {
                e.printStackTrace();
            }
            for (int i = 0; i < model.getRowCount(); i++) {
                if (!"Paid".equals(model.getValueAt(i, 7).toString())) {
                    txtPeriod.setText(model.getValueAt(i, 0).toString());
                    txtAmount.setText(model.getValueAt(i, 4).toString());
                    txtFine.setText(model.getValueAt(i, 3).toString());
                    Details newdetails = new Details();
                    newdetails = list.getdetail(Integer.parseInt(cbContract.getSelectedItem().toString()));
                    PlanPayment Plan = new PlanPayment();
                    int Paid = Plan.getremain(Integer.parseInt(cbContract.getSelectedItem().toString()));
                    double remain = newdetails.loanAmount - Paid;
                    NumberFormat fomat = new DecimalFormat("#,###.##");
                    txtRemain.setText(fomat.format(remain));

                    break;

                } else if (i == model.getRowCount() - 1) {

                    txtPeriod.setText("All Paid");
                    txtAmount.setText("All Paid");
                    btnPayment.setEnabled(false);
                    Details newdetails = new Details();
                    newdetails = list.getdetail(Integer.parseInt(cbContract.getSelectedItem().toString()));
                    PlanPayment Plan = new PlanPayment();
                    int Paid = Plan.getremain(Integer.parseInt(cbContract.getSelectedItem().toString()));
                    double remain = newdetails.loanAmount - Paid;
                    NumberFormat fomat = new DecimalFormat("#,###.##");
                    txtRemain.setText(fomat.format(remain));

                }
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnPaymentActionPerformed

    private void cbContractFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbContractFocusGained

        String inden = txtinden.getText().trim();
        ContractList list = new ContractList();

        cbmodel = (DefaultComboBoxModel) cbContract.getModel();
        cbmodel.removeAllElements();
        if (!list.getContractID(inden).isEmpty()) {
            for (Integer a : list.getContractID(inden)) {
                cbmodel.addElement(a);
            }
            CustomerList clist = new CustomerList();
            Customer cus = clist.getcus(inden);
            txtAdd.setText(cus.address);
            txtCompany.setText(cus.organization);
            txtName.setText(cus.name);
            txtDOB.setDate(cus.Dob);
            txtPhone.setText(cus.phone);
        } else {
            txtinden.requestFocus();
            JOptionPane.showMessageDialog(null, "Indentify not found !!!");

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_cbContractFocusGained

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPayment;
    private javax.swing.JComboBox cbContract;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbDetail;
    private javax.swing.JTextField txtAdd;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtCompany;
    private com.toedter.calendar.JDateChooser txtDOB;
    private javax.swing.JTextField txtFine;
    private javax.swing.JTextField txtLoan;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPeriod;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtRemain;
    private javax.swing.JTextField txtinden;
    // End of variables declaration//GEN-END:variables

    private void initModel() {
        model = (DefaultTableModel) tbDetail.getModel();
        sorter = (TableRowSorter<TableModel>) tbDetail.getRowSorter();
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(SwingConstants.RIGHT);
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        tbDetail.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        tbDetail.getColumnModel().getColumn(1).setCellRenderer(rightRenderer);
        tbDetail.getColumnModel().getColumn(2).setCellRenderer(rightRenderer);
        tbDetail.getColumnModel().getColumn(3).setCellRenderer(rightRenderer);
        tbDetail.getColumnModel().getColumn(4).setCellRenderer(rightRenderer);
        tbDetail.getColumnModel().getColumn(5).setCellRenderer(rightRenderer);
        tbDetail.getColumnModel().getColumn(6).setCellRenderer(centerRenderer);
        tbDetail.getColumnModel().getColumn(7).setCellRenderer(centerRenderer);
        tbDetail.setShowGrid(true);

        tbDetail.getTableHeader().setOpaque(false);
        tbDetail.getTableHeader().setBackground(Color.blue);
        tbDetail.getTableHeader().setForeground(Color.blue);
        FineList fl = new FineList();
        fList = fl.getList();
    }
}
