/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import data.ContractList;
import data.Customer;
import data.CustomerList;

import data.Request;
import data.RequestList;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

import java.text.DecimalFormat;
import java.text.NumberFormat;

import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author tndkh_000
 */
public class PnRequest extends javax.swing.JPanel {

    /**
     * Creates new form PnNewCustomer
     */
    public PnRequest() {
        initComponents();
    }
    JPanel PnShow;

    PnRequest(JPanel PnShow, String indent, int salary, double colateral, String loanType, int period, String loanStatus, String grade, int iRate, double maxLoan, int maxPeriod, int minPeriod) {
        this.PnShow = PnShow;
        initComponents();
        txtindentify.setText(indent);
        txtAcc.setEnabled(false);
        txtindentify.setEnabled(false);
        txtSalary.setEnabled(false);
        txtColl.setEnabled(false);
        spLoan.setModel(new javax.swing.SpinnerNumberModel(10000, 10000, maxLoan, 10000));
        spPeriod.setModel(new javax.swing.SpinnerNumberModel(minPeriod, minPeriod, maxPeriod, 1));

        NumberFormat formatphi = new DecimalFormat("#,###");
        txtSalary.setText(formatphi.format(salary));
        txtColl.setText(formatphi.format(colateral));
        txtLoanType.setText(loanType);

        txtLoanStatus.setText(loanStatus);
        txtGrade.setText(grade);
        txtIntRate.setText(Integer.toString(iRate));
        initData();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        birthdayEvaluator1 = new com.toedter.calendar.demo.BirthdayEvaluator();
        birthdayEvaluator2 = new com.toedter.calendar.demo.BirthdayEvaluator();
        jLocaleChooserBeanInfo1 = new com.toedter.components.JLocaleChooserBeanInfo();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        txtJob = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtColl = new javax.swing.JTextField();
        txtGrade = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtAcc = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtindentify = new javax.swing.JTextField();
        txtLoanStatus = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtLoanType = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtSalary = new javax.swing.JFormattedTextField();
        btnSend = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtDob = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        spPeriod = new javax.swing.JSpinner();
        txtPhone = new javax.swing.JFormattedTextField();
        txtIntRate = new javax.swing.JTextField();
        spLoan = new javax.swing.JSpinner();

        setBackground(new java.awt.Color(204, 255, 204));
        setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 255), new java.awt.Color(153, 153, 255)));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NEW REQUEST", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Agency FB", 1, 18), new java.awt.Color(51, 51, 255))); // NOI18N
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel9.setText("Loan Amount :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 0, 0);
        jPanel1.add(jLabel9, gridBagConstraints);

        jLabel6.setText("Period :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 125, 0, 0);
        jPanel1.add(jLabel6, gridBagConstraints);

        jLabel8.setText("Phone :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 45, 0, 0);
        jPanel1.add(jLabel8, gridBagConstraints);

        jLabel10.setText("Collateral :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 110, 0, 0);
        jPanel1.add(jLabel10, gridBagConstraints);

        txtAddress.setMaximumSize(new java.awt.Dimension(0, 30));
        txtAddress.setMinimumSize(new java.awt.Dimension(0, 30));
        txtAddress.setPreferredSize(new java.awt.Dimension(0, 30));
        txtAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAddressFocusGained(evt);
            }
        });
        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 360;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 16, 0, 0);
        jPanel1.add(txtAddress, gridBagConstraints);

        txtJob.setMaximumSize(new java.awt.Dimension(0, 30));
        txtJob.setMinimumSize(new java.awt.Dimension(0, 30));
        txtJob.setPreferredSize(new java.awt.Dimension(0, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 360;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 16, 0, 0);
        jPanel1.add(txtJob, gridBagConstraints);

        jLabel11.setText("Interest Rate :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 10, 0, 0);
        jPanel1.add(jLabel11, gridBagConstraints);

        txtName.setMaximumSize(new java.awt.Dimension(0, 30));
        txtName.setMinimumSize(new java.awt.Dimension(0, 30));
        txtName.setPreferredSize(new java.awt.Dimension(0, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 360;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 16, 0, 0);
        jPanel1.add(txtName, gridBagConstraints);

        txtColl.setMaximumSize(new java.awt.Dimension(0, 30));
        txtColl.setMinimumSize(new java.awt.Dimension(0, 30));
        txtColl.setPreferredSize(new java.awt.Dimension(0, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 360;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 17, 0, 0);
        jPanel1.add(txtColl, gridBagConstraints);

        txtGrade.setEnabled(false);
        txtGrade.setMaximumSize(new java.awt.Dimension(0, 30));
        txtGrade.setMinimumSize(new java.awt.Dimension(0, 30));
        txtGrade.setPreferredSize(new java.awt.Dimension(0, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 53;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 18, 0, 0);
        jPanel1.add(txtGrade, gridBagConstraints);

        jLabel16.setText("Grade : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 43, 0, 0);
        jPanel1.add(jLabel16, gridBagConstraints);

        txtAcc.setMaximumSize(new java.awt.Dimension(0, 30));
        txtAcc.setMinimumSize(new java.awt.Dimension(0, 30));
        txtAcc.setPreferredSize(new java.awt.Dimension(0, 30));
        txtAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAccActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 275;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(47, 16, 0, 0);
        jPanel1.add(txtAcc, gridBagConstraints);

        jLabel15.setText("Account No. :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(55, 16, 0, 0);
        jPanel1.add(jLabel15, gridBagConstraints);

        txtindentify.setMaximumSize(new java.awt.Dimension(0, 30));
        txtindentify.setMinimumSize(new java.awt.Dimension(0, 30));
        txtindentify.setName(""); // NOI18N
        txtindentify.setPreferredSize(new java.awt.Dimension(0, 30));
        txtindentify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtindentifyActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 360;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(47, 16, 0, 0);
        jPanel1.add(txtindentify, gridBagConstraints);

        txtLoanStatus.setEnabled(false);
        txtLoanStatus.setMaximumSize(new java.awt.Dimension(0, 30));
        txtLoanStatus.setMinimumSize(new java.awt.Dimension(0, 30));
        txtLoanStatus.setPreferredSize(new java.awt.Dimension(0, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 360;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 16, 0, 0);
        jPanel1.add(txtLoanStatus, gridBagConstraints);

        jLabel14.setText("Indentify Card :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(55, 86, 0, 0);
        jPanel1.add(jLabel14, gridBagConstraints);

        txtLoanType.setEnabled(false);
        txtLoanType.setMaximumSize(new java.awt.Dimension(0, 30));
        txtLoanType.setMinimumSize(new java.awt.Dimension(0, 30));
        txtLoanType.setPreferredSize(new java.awt.Dimension(0, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 14;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 275;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 18, 0, 112);
        jPanel1.add(txtLoanType, gridBagConstraints);

        jLabel13.setText("Loan Status : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 88, 0, 0);
        jPanel1.add(jLabel13, gridBagConstraints);

        jLabel7.setText("Salary :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 45, 0, 0);
        jPanel1.add(jLabel7, gridBagConstraints);

        jLabel5.setText("Company :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 110, 0, 0);
        jPanel1.add(jLabel5, gridBagConstraints);

        txtSalary.setMaximumSize(new java.awt.Dimension(0, 30));
        txtSalary.setMinimumSize(new java.awt.Dimension(0, 30));
        txtSalary.setPreferredSize(new java.awt.Dimension(0, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 275;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 16, 0, 0);
        jPanel1.add(txtSalary, gridBagConstraints);

        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 214, 41, 0);
        jPanel1.add(btnSend, gridBagConstraints);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 1, 41, 0);
        jPanel1.add(jButton2, gridBagConstraints);

        jLabel2.setText("Full Name :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 110, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        txtDob.setMaximumSize(new java.awt.Dimension(0, 30));
        txtDob.setMinimumSize(new java.awt.Dimension(0, 30));
        txtDob.setPreferredSize(new java.awt.Dimension(0, 30));
        txtDob.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDobKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 254;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 16, 0, 0);
        jPanel1.add(txtDob, gridBagConstraints);

        jLabel3.setText("DoB :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 56, 0, 0);
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabel12.setText("Loan Type : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 22, 0, 0);
        jPanel1.add(jLabel12, gridBagConstraints);

        jLabel4.setText("Address :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 116, 0, 0);
        jPanel1.add(jLabel4, gridBagConstraints);

        spPeriod.setModel(new javax.swing.SpinnerNumberModel());
        spPeriod.setMaximumSize(new java.awt.Dimension(30, 30));
        spPeriod.setMinimumSize(new java.awt.Dimension(30, 30));
        spPeriod.setPreferredSize(new java.awt.Dimension(30, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 43;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 17, 0, 0);
        jPanel1.add(spPeriod, gridBagConstraints);

        txtPhone.setMaximumSize(new java.awt.Dimension(0, 30));
        txtPhone.setMinimumSize(new java.awt.Dimension(0, 30));
        txtPhone.setPreferredSize(new java.awt.Dimension(0, 30));
        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });
        txtPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPhoneKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 275;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 16, 0, 0);
        jPanel1.add(txtPhone, gridBagConstraints);

        txtIntRate.setEnabled(false);
        txtIntRate.setMaximumSize(new java.awt.Dimension(0, 30));
        txtIntRate.setMinimumSize(new java.awt.Dimension(0, 30));
        txtIntRate.setPreferredSize(new java.awt.Dimension(0, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 122;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 18, 0, 112);
        jPanel1.add(txtIntRate, gridBagConstraints);

        spLoan.setMaximumSize(new java.awt.Dimension(0, 30));
        spLoan.setMinimumSize(new java.awt.Dimension(0, 30));
        spLoan.setPreferredSize(new java.awt.Dimension(0, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 109;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 16, 0, 0);
        jPanel1.add(spLoan, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed

        String iCard = txtindentify.getText().trim();

        String name = txtName.getText().trim();
        String Add = txtAddress.getText().trim();
        String organization = txtJob.getText().trim();
        String grade = txtGrade.getText().trim();
        String phone = txtPhone.getText().trim();
        int salary = Integer.parseInt(txtSalary.getText().trim().replaceAll("[\\.\\,]", ""));

        Calendar d = Calendar.getInstance();
        java.util.Date date = d.getTime();
        java.sql.Date sqlDatecon = new java.sql.Date(date.getTime());

        Double Collateral = Double.parseDouble(txtColl.getText().trim().replaceAll("[\\.\\,]", ""));
        int Period = (int) spPeriod.getValue();
        Double loanAmout = (Double) spLoan.getValue();
        String loanType = txtLoanType.getText().trim();
        String loanStatus = txtLoanStatus.getText().trim();
        int irate = Integer.parseInt(txtIntRate.getText());

        if (txtName.getText().trim().length() < 10) {
            JOptionPane.showMessageDialog(null, "Name's length must over 10");
            txtName.requestFocus();
        } else if (txtAddress.getText().trim().length() < 15) {
            JOptionPane.showMessageDialog(null, "Address's length must over 15");
            txtName.requestFocus();
        } else if (txtJob.getText().trim().length() < 1) {
            JOptionPane.showMessageDialog(null, "Company cannot blank");
            txtJob.requestFocus();
        } else if (txtPhone.getText().trim().length() < 9 || txtPhone.getText().trim().length() > 15) {
            JOptionPane.showMessageDialog(null, "Phone's lenght must more than 9 and less than 15");
            txtPhone.requestFocus();

        } else if (txtDob.getDateFormatString().isEmpty()) {
            JOptionPane.showMessageDialog(null, "DoB cannot blank");
            txtDob.requestFocus();
        } else {
            java.util.Date utilDate = new java.util.Date();
            utilDate = txtDob.getDate();
            java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
            Request o = new Request(0, Period, salary, name, iCard, Add, organization, phone, sqlDate, loanAmout, Collateral, loanType, grade, loanStatus, loanStatus, sqlDatecon, irate);
            RequestList list = new RequestList();
            list.insert(o);
            JOptionPane.showMessageDialog(null, "Add Request Success !!!");
            btnSend.setEnabled(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSendActionPerformed

    private void txtAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccActionPerformed

    private void txtindentifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtindentifyActionPerformed
        ContractList conl = new ContractList();
        String iCard = txtindentify.getText().trim();
        if (conl.getacc(iCard) == 0) {
            txtAcc.setText("NEW CUSTOMER");

        } else {
            Customer cus = new Customer();
            CustomerList cl = new CustomerList();
            cus = cl.getcus(iCard);
            txtAcc.setText(Integer.toString(cus.acc));
            txtindentify.setText(iCard);
            txtindentify.setEnabled(false);
            txtName.setText(cus.name);
            txtName.setEnabled(false);
            txtDob.setDate(cus.Dob);
            txtDob.setEnabled(false);
            txtAddress.setText(cus.address);
            txtAddress.setEnabled(false);
            txtPhone.setText(cus.phone);
            txtPhone.setEnabled(false);
            txtJob.setText(cus.organization);
            txtJob.setEnabled(false);

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_txtindentifyActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtAddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAddressFocusGained
        checkdob();

// TODO add your handling code here:
    }//GEN-LAST:event_txtAddressFocusGained

    private void txtDobKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDobKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDobKeyPressed

    private void txtPhoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneKeyPressed
        txtPhone.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char vChar = e.getKeyChar();
                if (!(Character.isDigit(vChar)
                        || (vChar == KeyEvent.VK_BACK_SPACE)
                        || (vChar == KeyEvent.VK_DELETE))) {
                    e.consume();
                }
            }
        });          // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        PnShow.removeAll();
        PnCheckGrade a = new PnCheckGrade(PnShow);
        PnShow.add(a);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.demo.BirthdayEvaluator birthdayEvaluator1;
    private com.toedter.calendar.demo.BirthdayEvaluator birthdayEvaluator2;
    private javax.swing.JButton btnSend;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.toedter.components.JLocaleChooserBeanInfo jLocaleChooserBeanInfo1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner spLoan;
    private javax.swing.JSpinner spPeriod;
    private javax.swing.JTextField txtAcc;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtColl;
    private com.toedter.calendar.JDateChooser txtDob;
    private javax.swing.JTextField txtGrade;
    private javax.swing.JTextField txtIntRate;
    private javax.swing.JTextField txtJob;
    private javax.swing.JTextField txtLoanStatus;
    private javax.swing.JTextField txtLoanType;
    private javax.swing.JTextField txtName;
    private javax.swing.JFormattedTextField txtPhone;
    private javax.swing.JFormattedTextField txtSalary;
    private javax.swing.JTextField txtindentify;
    // End of variables declaration//GEN-END:variables

    private void initData() {
        ContractList conl = new ContractList();
        String iCard = txtindentify.getText().trim();
        if (conl.getacc(iCard) == 0) {
            txtAcc.setText("NEW CUSTOMER");

        } else {
            Customer cus = new Customer();
            CustomerList cl = new CustomerList();
            cus = cl.getcus(iCard);
            txtAcc.setText(Integer.toString(cus.acc));
            txtindentify.setText(iCard);
            txtName.setText(cus.name);
            txtDob.setDate(cus.Dob);
            txtAddress.setText(cus.address);
            txtPhone.setText(cus.phone);
            txtJob.setText(cus.organization);
            txtindentify.setEnabled(false);
            txtName.setEnabled(false);
            txtDob.setEnabled(false);
            txtAddress.setEnabled(false);
            txtPhone.setEnabled(false);
            txtJob.setEnabled(false);
            txtAcc.setEnabled(false);

        }
    }

    private void checkdob() {
        Calendar dob = Calendar.getInstance();
        try {
            dob.setTime(txtDob.getDate());
            Calendar today = Calendar.getInstance();
            int age = today.get(Calendar.YEAR) - dob.get(Calendar.YEAR);
            if (today.get(Calendar.MONTH) < dob.get(Calendar.MONTH)) {
                age--;
            } else if (today.get(Calendar.MONTH) == dob.get(Calendar.MONTH) && today.get(Calendar.DAY_OF_MONTH) < dob.get(Calendar.DAY_OF_MONTH)) {
                age--;
            }

            if (age < 18) {
                txtDob.requestFocus();
                JOptionPane.showMessageDialog(null, "Customer must over 18 years old");

            }
            if (age > 80) {
                txtDob.requestFocus();
                JOptionPane.showMessageDialog(null, "Not support customer over 80 years old");
            }
        } catch (Exception e) {
            txtDob.requestFocus();
            JOptionPane.showMessageDialog(null, "Date format is incorrect");

        }

    }
}
