/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import data.Details;
import data.DetailsList;
import data.PlanPayment;
import java.awt.Color;

import java.text.DecimalFormat;
import java.text.NumberFormat;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author tndkh_000
 */
public class PnTracking extends javax.swing.JPanel {

    /**
     * Creates new form PnDetail
     */
    public PnTracking() {
        initComponents();
        initData();
        txtInden.setEnabled(false);
        txtLoan.setEnabled(false);
        txtName.setEnabled(false);
        txtNgayvay.setEnabled(false);
        txtPeriod.setEnabled(false);
        txtRemain.setEnabled(false);
        txtAccNo.setEnabled(false);
    }
    
    public PnTracking(Integer contractID) {
        initComponents();
        initData();
        txtInden.setEnabled(false);
        txtLoan.setEnabled(false);
        txtName.setEnabled(false);
        txtNgayvay.setEnabled(false);
        txtPeriod.setEnabled(false);
        txtRemain.setEnabled(false);
        txtAccNo.setEnabled(false);
        txtAccNo.setText(contractID.toString());
        this.setValues(contractID);
    }
  
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        txtInden = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAccNo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtLoan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPeriod = new javax.swing.JTextField();
        txtRemain = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNgayvay = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDetail = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 255), new java.awt.Color(153, 153, 255)));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CUSTOMER DETAILS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 18), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        txtInden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIndenActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 104;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 37, 0, 0);
        jPanel1.add(txtInden, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 119;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 4, 0, 0);
        jPanel1.add(txtName, gridBagConstraints);

        jLabel2.setText("Contrac No. :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 17, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        txtAccNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAccNoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 119;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 4, 0, 0);
        jPanel1.add(txtAccNo, gridBagConstraints);

        jLabel1.setText("Name :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 76;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 17, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel3.setText("Indentify Card :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 32, 0, 0);
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabel4.setText("Loan Amout :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 17, 0, 0);
        jPanel1.add(jLabel4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 119;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 4, 7, 0);
        jPanel1.add(txtLoan, gridBagConstraints);

        jLabel5.setText("Period :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 32, 0, 0);
        jPanel1.add(jLabel5, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 104;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 37, 7, 0);
        jPanel1.add(txtPeriod, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 104;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 13, 7, 36);
        jPanel1.add(txtRemain, gridBagConstraints);

        jLabel6.setText("Remaining Amout :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 42, 0, 0);
        jPanel1.add(jLabel6, gridBagConstraints);

        txtNgayvay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayvayActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 104;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 13, 0, 36);
        jPanel1.add(txtNgayvay, gridBagConstraints);

        jLabel7.setText("Ngày Vay :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 42, 0, 0);
        jPanel1.add(jLabel7, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.BorderLayout());

        tbDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Period", "Principal/Period", "Interes/Period", "Fine", "Amount", "Remain", "Payment Due", "Status", "Payment Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbDetail.setGridColor(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(tbDetail);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIndenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIndenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIndenActionPerformed

    private void txtNgayvayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayvayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayvayActionPerformed

    private void txtAccNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAccNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccNoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbDetail;
    private javax.swing.JTextField txtAccNo;
    private javax.swing.JTextField txtInden;
    private javax.swing.JTextField txtLoan;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNgayvay;
    private javax.swing.JTextField txtPeriod;
    private javax.swing.JTextField txtRemain;
    // End of variables declaration//GEN-END:variables
    DefaultTableModel model;
    TableRowSorter<TableModel> sorter;
    
    private void initData() {
        model = (DefaultTableModel) tbDetail.getModel();
        sorter = (TableRowSorter<TableModel>) tbDetail.getRowSorter();
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(SwingConstants.RIGHT);
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        tbDetail.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        tbDetail.getColumnModel().getColumn(1).setCellRenderer(rightRenderer);
        tbDetail.getColumnModel().getColumn(2).setCellRenderer(rightRenderer);
        tbDetail.getColumnModel().getColumn(3).setCellRenderer(rightRenderer);
        tbDetail.getColumnModel().getColumn(4).setCellRenderer(rightRenderer);
        tbDetail.getColumnModel().getColumn(5).setCellRenderer(centerRenderer);
        tbDetail.getColumnModel().getColumn(6).setCellRenderer(centerRenderer);
        tbDetail.setShowGrid(true);

        tbDetail.getTableHeader().setOpaque(false);
        tbDetail.getTableHeader().setBackground(Color.blue);
        tbDetail.getTableHeader().setForeground(Color.blue);

//        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
//        headerRenderer.setBackground(Color.blue);
//        headerRenderer.setForeground(Color.white);
//        
//        for (int i = 0; i < tbDetail.getModel().getColumnCount(); i++) {
//            tbDetail.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
//        }
    }
    private void setValues(int contractID){
        DetailsList list = new DetailsList();
        Details newdetails = new Details();
        newdetails = list.getdetail(contractID);
        txtInden.setText(newdetails.indent);

        txtName.setText(newdetails.name);
        txtPeriod.setText(Integer.toString(newdetails.period));
        PlanPayment Plan = new PlanPayment();
        int Paid = Plan.getremain(contractID);
        double remain = newdetails.loanAmount - Paid;
        NumberFormat fomat = new DecimalFormat("#,###.##");
        txtLoan.setText(fomat.format(newdetails.loanAmount));
        txtRemain.setText(fomat.format(remain));
        txtNgayvay.setText(newdetails.date);

        model.setRowCount(0);
        PlanPayment bl = new PlanPayment();
        for (PlanPayment item : bl.getacc(contractID)) {
            model.addRow(item.toVector2());

        }
    }
}
